### ISSUE TITLE
Shooter Example not updated to recent API changes

### ISSUE THREAD

**Issue by yutotakano** [asivitz/Hickory#2]
Hickory looks very cool and innovative; I'd very much love to play around with it! Unfortunately, it seems like the shooter example uses some functions and APIs that are no longer part of the current Hickory, and it fails to build after I pulled the latest master branch.

Specifically, things like `withAttrVal` and `GlobalSettings` are causing build failures.

Would you mind updating the example when you have the time?

**Comment by asivitz** [comment]
Ah sorry about that. Should be good to go now
